# NumPy

Read the link https://numpy.org/doc/stable/user/quickstart.html before starting the exercises. 

In [4]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [5]:
A = np.arange(1, 16).reshape(3,5)
print("Matrix A:")
print(A)
print("\nDimension (antal axlar):", A.ndim)
print("Shape (rader, kolumner):", A.shape)
print("Size (totalt antal element):", A.size)
print("Datatype:", A.dtype)


Matrix A:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Dimension (antal axlar): 2
Shape (rader, kolumner): (3, 5)
Size (totalt antal element): 15
Datatype: int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [6]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

# Elementwise subtraction
subtraction = B - C
print("\nElementwise subtraction (B - C):")
print(subtraction)

# Elementwise multiplication
elementwise_mul = B * C
print("\nElementwise multiplication (B * C):")
print(elementwise_mul)

# Matrix multiplication
matrix_mul = B @ C
print("\nMatrix multiplication (B @ C):")
print(matrix_mul)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]

Elementwise subtraction (B - C):
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Elementwise multiplication (B * C):
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix multiplication (B @ C):
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on matrix D:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [7]:
D = np.arange(1, 10).reshape(3, 3)
print(D)

# Elementwise exponentiation
exp_D = np.exp(D)
print("\nElementwise exponentiation (np.exp(D)):")
print(exp_D)

# Minimum value
min_all = np.min(D)
print("\nMinimum value in whole matrix:", min_all)

# Minimum per row
min_rows = np.min(D, axis=1)
print("\nMinimum value in each row:", min_rows)

# Minimum per column
min_cols = np.min(D, axis=0)
print("\nMinimum value in each column:", min_cols)

# Index of minimum value (whole matrix)
argmin_all = np.argmin(D)
print("\nIndex of minimum value in whole matrix:", argmin_all)

row, col = np.unravel_index(np.argmin(D), D.shape)
print("Row, column index of minimum value:", row, col)

# Index of minimum value in each row
argmin_rows = np.argmin(D, axis=1)
print("\nIndex of minimum value in each row:", argmin_rows)

# Sum of all elements
sum_all = np.sum(D)
print("\nSum of all elements:", sum_all)

# Mean of each column
mean_cols = np.mean(D, axis=0)
print("\nMean of each column:", mean_cols)

# Median of each column
median_cols = np.median(D, axis=0)
print("\nMedian of each column:", median_cols)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Elementwise exponentiation (np.exp(D)):
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minimum value in whole matrix: 1

Minimum value in each row: [1 4 7]

Minimum value in each column: [1 2 3]

Index of minimum value in whole matrix: 0
Row, column index of minimum value: 0 0

Index of minimum value in each row: [0 0 0]

Sum of all elements: 45

Mean of each column: [4. 5. 6.]

Median of each column: [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [ ]:
print(A)

In [ ]:
A[1]

**Answer:**

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [10]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [9]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [11]:
for elem in A.flat:
    print(elem)


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [13]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


### Broadcasting
Read the link https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting and the document *"matematik_yh_kap_10"* (solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh) before starting the exercises below.  

If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

##### Remark on Broadcasting when doing Linear Algebra calculations in Python. 
From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices.

In [14]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [15]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [16]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


### Vector and matrix algebra

Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.

Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).

In [17]:
def add_mult_matrices(m1, m2, operation):
    # Validate input types
    if not isinstance(m1, np.ndarray) or not isinstance(m2, np.ndarray):
        raise TypeError("Both inputs must be numpy.ndarray")

    # Validate operation
    if operation not in ["add", "multiply"]:
        raise ValueError("Operation must be 'add' or 'multiply'")

    # Matrix addition
    if operation == "add":
        if m1.shape != m2.shape:
            raise ValueError("For addition, matrices must have the same shape")
        return m1 + m2

    # Matrix multiplication
    if operation == "multiply":
        if m1.shape[1] != m2.shape[0]:
            raise ValueError(
                "For multiplication, number of columns in first matrix "
                "must equal number of rows in second matrix"
            )
        return m1 @ m2

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. Note, the function you created above can be used. 

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

### Copies and Views
Read the link https://numpy.org/doc/stable/user/basics.copies.html before starting the exercises below. 

Basic indexing creates a view. How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?

In [18]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

print(v2.base is v1)  # True → v2 is a view

v2[-1] = 123

print(v1)
print(v2)


[0 1 2 3]
[2 3]
True
[  0   1   2 123]
[  2 123]
